### ISSUE TITLE
RobotRaconteur.RobotRaconteurNETPINVOKE exception error 

### ISSUE THREAD

**Issue by nrsprs** [robotraconteur-contrib/URRobotRaconteurDriver#1]
Hi, I'm trying to build the URRobotRaconteurDrivers and get the error below when I cast this command from the build tutorial:
> dotnet URRobotRaconteurDriver.dll --robt-info-file=../ur10e_robot_default_config.yml --robot-hostname="192.168.1.102"

System info:
RID: ubuntu.22.04-x64 
.NET version: 3.1.426 
Robot: ur10e 
librobotraconteur-net-native version: 0.18.0-1~jammy 

I feel like I'm missing something, but can't figure out why these errors are appearing. The first dotnet command was successful with two warnings about unassigned variables URScriptProgramSender.keep_going within the .csproj file. 

Here's the error: 
> nxsgis@rosie:~/workspace/robot-raconteur/URRobotRaconteurDriver/build$ dotnet URRobotRaconteurDriver.dll --robot-info-file=../ur10e_robot_default_config.yml --robot-hostname=192.168.1.102
Unhandled exception. System.TypeInitializationException: The type initializer for 'RobotRaconteur.RobotRaconteurNETPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'RobotRaconteurNETNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libRobotRaconteurNETNative: cannot open shared object file: No such file or directory
   at RobotRaconteur.RobotRaconteurNETPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_RobotRaconteurNET(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at RobotRaconteur.RobotRaconteurNETPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at RobotRaconteur.RobotRaconteurNETPINVOKE.SWIGExceptionHelper..ctor()
   at RobotRaconteur.RobotRaconteurNETPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at RobotRaconteur.RobotRaconteurNETPINVOKE.NodeID_NewUniqueID()
   at RobotRaconteur.NodeID.NewUniqueID()
   at RobotRaconteur.Companion.Util.LocalIdentifiersManager.GetIdentifierForNameAndLock(String category, String name)
   at RobotRaconteur.Companion.InfoParser.RobotInfoParser.LoadRobotInfoYamlWithIdentifierLocks(YamlRobotInfo yaml_robot_info, String device_name_override)
   at RobotRaconteur.Companion.InfoParser.RobotInfoParser.LoadRobotInfoYamlWithIdentifierLocks(String filename, String device_name_override)
   at URRobotRaconteurDriver.Program.Main(String[] args) in /home/nxsgis/workspace/robot-raconteur/URRobotRaconteurDriver/Program.cs:line 97
Aborted (core dumped)

Hope this is enough information for troubleshooting. TYIA.

**Comment by johnwason** [comment]
The native library needs to be installed separately on Linux. Here are instructions:

https://github.com/robotraconteur/robotraconteur/blob/master/docs/common/installation.md#ubuntu-xenial-bionic-focal-and-jammy

**Comment by nrsprs** [comment]
I believe that I've installed the native library properly.

When I check my deb ppas, they appear:
> /etc/apt/sources.list.d/robotraconteur-ubuntu-ppa-jammy.list:deb https://ppa.launchpadcontent.net/robotraconteur/ppa/ubuntu/ jammy main
> /etc/apt/sources.list.d/robotraconteur-ubuntu-ppa-jammy.list:# deb-src https://ppa.launchpadcontent.net/robotraconteur/ppa/ubuntu/ jammy main


When attempting to install, I get this message:
> librobotraconteur-net-native is already the newest version (0.18.0-1~jammy).

The error from the dotnet command looks like this:
> nxsgis@rosie:~/workspace/robot-raconteur/URRobotRaconteurDriver/build$ dotnet URRobotRaconteurDriver.dll --robot-info-file=../ur10e_robot_default_config.yml --robot-hostname=192.168.1.102
Unhandled exception. System.TypeInitializationException: The type initializer for 'RobotRaconteur.RobotRaconteurNETPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'RobotRaconteurNETNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable:
 
What do you think I'm doing wrong that the .dll can't find the RRNETNative lib? 

Here's the rest of the output..
 > libRobotRaconteurNETNative: cannot open shared object file: No such file or directory
   at RobotRaconteur.RobotRaconteurNETPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_RobotRaconteurNET(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at RobotRaconteur.RobotRaconteurNETPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at RobotRaconteur.RobotRaconteurNETPINVOKE.SWIGExceptionHelper..ctor()
   at RobotRaconteur.RobotRaconteurNETPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at RobotRaconteur.RobotRaconteurNETPINVOKE.NodeID_NewUniqueID()
   at RobotRaconteur.NodeID.NewUniqueID()
   at RobotRaconteur.Companion.Util.LocalIdentifiersManager.GetIdentifierForNameAndLock(String category, String name)
   at RobotRaconteur.Companion.InfoParser.RobotInfoParser.LoadRobotInfoYamlWithIdentifierLocks(YamlRobotInfo yaml_robot_info, String device_name_override)
   at RobotRaconteur.Companion.InfoParser.RobotInfoParser.LoadRobotInfoYamlWithIdentifierLocks(String filename, String device_name_override)
   at URRobotRaconteurDriver.Program.Main(String[] args) in /home/nxsgis/workspace/robot-raconteur/URRobotRaconteurDriver/Program.cs:line 97
Aborted (core dumped)

Any further support with this would be much appreciated.  Thank you.

**Comment by johnwason** [comment]
What version of dotnet runtime are you using?

**Comment by nrsprs** [comment]
I'm using 3.1.426 for Ubuntu 22.04.

**Comment by johnwason** [comment]
I am trying to reproduce the error, but cannot install dotnet 3.1 on my Ubuntu 22.04 system. Apparently it is no longer supported? What method did you use to install dotnet? We used Ubuntu 20.04 when developing the driver.

**Comment by nrsprs** [comment]
I used the snap package manager and selected the 3.1 channel. Snap 3.1 is no longer supported. The list of downloadable packages can be found using:
> snap info dotnet-sdk 

Install command:
> snap install dotnet-sdk --channel=3.1/stable

I'll try using Ubuntu 20.04. What method did you use to install dotnet on your 20.04 machine?

**Comment by johnwason** [comment]
Thank you for clarifying about snap. Because of the way snap works, I do not think it will be able to find the native library. Snap creates an isolated environment, with its own shared libraries that are incompatible with the rest of the system.

I can put together a docker for this driver to avoid these versioning problems. Would you be able to use a docker image?

**Comment by nrsprs** [comment]
Yes, that would be very helpful. Thank you.

**Comment by johnwason** [comment]
@nrsprs I have run into an unexpected error with running the driver on Linux. I should have something ready by Monday or Tuesday of next week. In the interim, I think the driver should work on Windows without any issues. Sorry about the problems, we have not used this driver for a while.

**Comment by johnwason** [comment]
I have created a docker for the driver. Please try:

```
sudo docker run -it --rm --net=host -v /var/run/robotraconteur:/var/run/robotraconteur -v /var/lib/robotraconteur:/var/lib/robotraconteur -e ROBOT_HOSTNAME=192.168.1.221 -e ROBOT_INFO_FILE=/config/ur5e_robot_default_config.yml  --privileged  docker.io/wasontech/ur-robotraconteur-driver
```

Replace the values for `ROBOT_INFO_FILE` and `ROBOT_HOSTNAME` with the relevant values. You may need to also use -v to mount a directory if you have a different config file that is not part of the docker.

**Comment by johnwason** [comment]
I used Ubuntu 22.04. Can you describe the alerts? It may be the autodiscovery UDP multicast packets.

**Comment by nrsprs** [comment]
The alerts are about a quarantined bash from:
> /var/lib/docker/overlay2/really long serial/merged/usr/bin/bash 

The command line arg was: 
> /bin/bash -lic echo -n another really long, different serial number

Either way, I've hit a blocking point in using the URR.dll, when using the command calling for the ur5e config, I get this error message:
> (rr_training_sim) root@rosie:~/workspace/robot_raconteur/URRobotRaconteurDriver/build# dotnet URRobotRaconteurDriver.dll --robot-info-file=../ur5e_robot_default_config.yml --robot-hostname=192.168.1.102
[2023-11-14T18:09:08.211536] [error] [0x7f831ac39740] [unknown] [transport] [-1] [LocalTransport.cpp:794] LocalTransport could not start server: Identifier UUID or Name already in use
Unhandled exception. System.ApplicationException: Identifier UUID or Name already in use
   at RobotRaconteur.WrappedRobotRaconteurNodeSetup..ctor(RobotRaconteurNode node, String node_name, UInt16 tcp_port, UInt32 flags, UInt32 allowed_overrides, vectorstring args)
   at RobotRaconteur.RobotRaconteurNodeSetup..ctor(String node_name, UInt16 tcp_port, RobotRaconteurNodeSetupFlags flags, RobotRaconteurNodeSetupFlags allowed_overrides, String[] args)
   at RobotRaconteur.ServerNodeSetup..ctor(String node_name, UInt16 tcp_port, String[] args)
   at URRobotRaconteurDriver.Program.Main(String[] args) in /root/workspace/robot_raconteur/URRobotRaconteurDriver/Program.cs:line 113
Aborted (core dumped)

When I try to cast it for the robot I'm using, I receive this error:
> (rr_training_sim) root@rosie:~/workspace/robot_raconteur/URRobotRaconteurDriver/build# dotnet URRobotRaconteurDriver.dll --robot-info-file=../ur10e_robot_default_config.yml --robot-hostname=192.168.1.102
Unhandled exception. RobotRaconteurException: RobotRaconteur.SystemResourceError: Could not initialize local identifiers
Aborted (core dumped)

Looking at the yaml files, it seems like everything is sound. I haven't touched those files. Tried rebuilding again, no luck. Any thoughts?

**Comment by johnwason** [comment]
These errors suggest you are trying to run more than one robot. Is that the case?

**Comment by nrsprs** [comment]
I don't believe so. Is there a way for me to check whether there are existing robots running using RR?

**Comment by johnwason** [comment]
You can run `ps x` to check if there is another instance of the driver running. The driver locks the node name and id, so that is the first error you are seeing.

**Comment by johnwason** [comment]
Are you from RIT?

**Comment by nrsprs** [comment]
yep! Greetings from Rochester!

**Comment by johnwason** [comment]
The URRobotRaconteurDriver code has been updated to the latest versions of Robot Raconteur and the companion library that should fix the issues you are having. It is now using dotnet 6.0 which should be easier to install. The docker instructions are in the readme.

Sorry for the delay getting this fixed. I found a few issues that required several upstream releases.
